app_jull/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls")),
    path("", include("app_photo.urls")),
    path("", include("notes.urls")),
    path("users/", include("users.urls")),
]

app_photo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'app_photo'

urlpatterns = [
    path('users/profile/gallery/upload/', views.upload, name='upload'),
    path('users/profile/gallery/', views.show_images, name='gallery'),
    path('users/profile/gallery/delete/<int:image_id>/', views.delete_image, name='remove_image'),
    path('users/profile/gallery/edit/<int:image_id>/', views.edit_image, name='edit_image'),
    path('users/profile/gallery/download/<int:image_id>/', views.download_image, name='download_image'),
    path('users/profile/gallery/my_photo', views.show_all_photo, name='show_photo'),
    path('users/profile/gallery/my_video', views.show_all_video, name='show_video'),
    path('users/profile/gallery/another', views.show_all_another, name='show_another'),
    path('users/profile/gallery/<int:page>', views.show_images, name='paginator_gallery'),
    path('users/profile/gallery/my_photo/<int:page>', views.show_all_photo, name='paginator_show_photo'),
    path('users/profile/gallery/my_video/<int:page>', views.show_all_video, name='paginator_show_video'),
    path('users/profile/gallery/another/<int:page>', views.show_all_another, name='paginator_show_another')
]

news/urls.py
from django.urls import path

from . import views
from users import views as users_views

app_name = "news"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", users_views.loginuser, name="login"),
    path("articles/", views.all_articles, name="all_articles"),
    path("article/<str:title>", views.one_article, name="one_article"),
    path("siences/", views.all_siences, name="all_siences"),
    path("sience/<str:title>", views.one_sience, name="one_sience"),
    path("technos/", views.all_technos, name="all_technos"),
    path("techno/<str:title>", views.one_techno, name="one_techno"),
    path("sports/", views.all_sports, name="all_sports"),
    path("sport/<str:title>", views.one_sport, name="one_sport"),
    path("usds/", views.all_banks_usd, name="all_banks_usd"),
    path("eurs/", views.all_banks_eur, name="all_banks_eur"),
    path("weather/", views.all_weather_cities, name="all_weather_cities"),
    path("weather/details", views.all_weather_details, name="all_weather_details"),
]

app_photo/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.contrib.auth import get_user_model



# Create your models here.


class Picture(models.Model):
    description = models.CharField(max_length=200)
    image = models.FileField(upload_to='photo_for_users',max_length=500)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,null=True)

app_photo/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, CharField, ImageField, TextInput, FileInput, FileField

from .models import Picture


def validate_file_size(value):
    # Максимальный размер файла в байтах (10 МБ)
    max_size = 10 * 1024 * 1024  # 10 МБ

    if value.size > max_size:
        raise ValidationError(f"Максимальный размер файла - 10 МБ. Ваш файл слишком большой ({value.size} байт).")



class FormPicture(ModelForm):
    description = CharField(max_length=200,widget=TextInput(attrs={'class':'form-control', 'id':'exampleInputEmail1'}))
    image = FileField(widget=FileInput(attrs={'class':'form-control', 'id':'formFile'}),validators=[validate_file_size])

    class Meta:
        model = Picture
        fields = ['description', 'image']

app_photo/views.py
import cloudinary.uploader
import requests
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FormPicture
from .models import Picture
from os.path import splitext
import cloudinary



def get_file_type(url):
    _, ext = splitext(url)
    if ext.lower() in ['.jpg', '.jpeg', '.png', '.gif']:
        return 'image'
    elif ext.lower() in ['.txt']:
        return 'text'
    elif ext.lower() in ['.mp4', '.avi', '.mov']:
        return 'video'
    else:
        return 'unknown'

# def show_images(request):
#     images = Picture.objects.all()
#
#     image_data = [
#         {
#             'url': image.image.url,
#             'description': image.description,
#             'id': image.id,
#             'file_type': get_file_type(image.image.url)
#         } for image in images
#     ]
#
#
#     return render(request, 'app_photo/image_gallery.html', {'image_data': image_data})



def upload(request):

    if request.method == 'POST':
        form = FormPicture(request.POST, request.FILES)
        if form.is_valid():
            # Получаем файл из формы
            file = request.FILES.get('image')
            if file:
                # Загружаем файл на Cloudinary
                uploaded_file = cloudinary.uploader.upload(file, resource_type="raw")

                # Сохраняем описание и URL загруженного файла в модели Picture
                picture = form.save(commit=False)
                picture.description = form.cleaned_data['description']
                picture.image = uploaded_file['secure_url']  # URL загруженного файла
                picture.user=request.user
                picture.save()
                form.add_error('image','File was successfully uploaded')

                return redirect('app_photo:gallery')
    else:
        form = FormPicture()
    return render(request, 'app_photo/upload.html', {'form': form})



def delete_image(request, image_id):
    try:
        image = Picture.objects.get(id=image_id)
        image.image.delete()
        image.delete()
        return redirect(to='app_photo:gallery')
    except Picture.DoesNotExist:
        return redirect(to='app_photo:gallery')


def edit_image(request,image_id):
    if request.method == 'POST':
        desc=request.POST.get('description')
        Picture.objects.filter(id=image_id).update(description=desc)

        return redirect(to='app_photo:gallery')
    data=Picture.objects.filter(id=image_id).first()

    return render(request,'app_photo/edit_form.html',context={'data':data})



def download_image(request, image_id):
    try:
        # Получаем объект Picture по его идентификатору
        picture = Picture.objects.get(id=image_id)
        # Получаем URL изображения из поля image объекта Picture
        image_url = picture.image.url
        # Получаем содержимое изображения по его URL с помощью запроса
        response = requests.get(image_url)
        # Получаем расширение файла изображения из его URL
        type_file=picture.image.url.split('.').pop()
        # Создаем HTTP-ответ с содержимым изображения
        http_response = HttpResponse(response.content, content_type='image/jpeg')
        # Устанавливаем заголовок для скачивания
        http_response['Content-Disposition'] = f'attachment; filename={picture.description}.{type_file}'
        return http_response
    except Exception as e:
        # Обработка ошибок, если изображение не найдено или произошла другая ошибка
        return HttpResponse("Error: " + str(e))

def show_all_photo(request,page=1):
    user=request.user
    images = Picture.objects.filter(user=user)

    image_data = [
        {
            'url': image.image.url,
            'description': image.description,
            'id': image.id,
            'file_type': get_file_type(image.image.url)
        } for image in images if get_file_type(image.image.url) == 'image'
    ]
    paginator = Paginator(image_data, 6)
    try:
        image_data = paginator.page(page)
    except PageNotAnInteger:
        image_data = paginator.page(1)
    except EmptyPage:
        image_data = paginator.page(paginator.num_pages)


    return render(request, 'app_photo/photos.html', {'image_data': image_data})


def show_all_video(request, page=1):
    user=request.user
    # Получаем все изображения из базы данных
    images = Picture.objects.filter(user=user)

    # Фильтруем изображения, оставляя только видеофайлы
    video_images = [
        {
            'url': image.image.url,
            'description': image.description,
            'id': image.id,
            'file_type': get_file_type(image.image.url)
        } for image in images if get_file_type(image.image.url) == 'video'
    ]

    # Разбиваем список видеофайлов на страницы
    paginator = Paginator(video_images, 6)
    try:
        video_images_page = paginator.page(page)
    except PageNotAnInteger:
        # Если номер страницы не целое число, показываем первую страницу
        video_images_page = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше максимального, показываем последнюю страницу
        video_images_page = paginator.page(paginator.num_pages)

    # Отображаем шаблон с отфильтрованными видеофайлами на первой странице
    return render(request, 'app_photo/videos.html', {'image_data': video_images_page})

def show_all_another(request,page=1):
    user = request.user
    images = Picture.objects.filter(user=user)

    image_data = [
        {
            'url': image.image.url,
            'description': image.description,
            'id': image.id,
            'file_type': get_file_type(image.image.url)
        } for image in images if get_file_type(image.image.url) != 'video' and get_file_type(image.image.url) != 'image'
    ]
    paginator = Paginator(image_data, 6)
    try:
        image_data = paginator.page(page)
    except PageNotAnInteger:
        image_data = paginator.page(1)
    except EmptyPage:
        image_data = paginator.page(paginator.num_pages)


    return render(request, 'app_photo/another_files.html', {'image_data': image_data})


def show_images(request,page=1):
    user = request.user
    images = Picture.objects.filter(user=user)

    image_data = [
        {
            'url': image.image.url,
            'description': image.description,
            'id': image.id,
            'file_type': get_file_type(image.image.url)
        } for image in images
    ]

    paginator = Paginator(image_data, 6)
    try:
        image_data = paginator.page(page)
    except PageNotAnInteger:
        image_data = paginator.page(1)
    except EmptyPage:
        image_data = paginator.page(paginator.num_pages)

    return render(request, 'app_photo/image_gallery.html', {'image_data': image_data})

app_photo/templates/app_photo/another_files.html
{% extends "users/base_form.html" %}
{% block content %}
<style>
    .card {
        height: 100%;
        display: flex;
        flex-direction: column;
        margin-bottom: 20px; /* Добавим отступ между карточками */
    }

    .card-img-top {
        flex: 1;
        object-fit: cover;
    }

    .card-body {
        flex-grow: 0;
    }

    .card-text {
        margin-bottom: 0;
    }

    /* Стили для кнопок внутри карточки */
    .card-buttons {
        display: flex;
        justify-content: space-between; /* Равномерно распределяем кнопки по ширине */
    }
    .custom-btn {
        display: inline-block;
        padding: 8px 16px; /* увеличим отступы для кнопок */
        margin-bottom: 0;
        font-size: 16px; /* увеличим размер шрифта */
        font-weight: 400;
        line-height: 1.5;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        cursor: pointer;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        color: #fff;
        background-color: #007bff; /* изменяем фон кнопки на синий цвет */
        border-color: #007bff;
        min-width: 120px; /* установим минимальную ширину для кнопок */
    }

    .custom-btn:not(:last-child) {
        margin-right: 8px; /* уменьшим расстояние между кнопками */
    }
</style>
<div class="container">
    <h1>Інші файли:</h1>
    <div class="row">
        {% for data in image_data %}
        <div class="col-md-6">
            <div class="card" style="width: 18rem;">
                {% if not data.file_type == 'image' and not data.file_type == 'video' %}
                 <span style="font-size: 5rem;">📄</span> <!-- Используем символ для текстового файла -->

                <img src="{{ data.url }}" class="card-img-top" alt="{{ data.description }}">
                <div class="card-body">
                    <p class="card-text">{{ data.description }}</p>
                    <a href="{% url 'app_photo:edit_image' data.id %}" class="custom-btn">Edit</a>
                    <a href="{% url 'app_photo:remove_image' data.id %}" class="custom-btn">Delete</a>
                    <a href="{% url 'app_photo:download_image' data.id %}" class="custom-btn">Download</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
<nav class="pagination-nav">
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not image_data.has_previous %} disabled {% endif %}"
                       href="{% if image_data.has_previous %} {% url 'app_photo:paginator_show_another' image_data.previous_page_number %} {% else %} # {% endif %}">Previous<span aria-hidden="true">→</span></a>
                </li>
                <li class="next">
                    <a class="{% if not image_data.has_next %} disabled {% endif %}"
                       href="{% if image_data.has_next %} {% url 'app_photo:paginator_show_another' image_data.next_page_number %} {% else %} # {% endif %}">Next
                        <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
{% endblock %}

app_photo/templates/app_photo/edit_form.html
{% extends "users/base_form.html" %}
{%block content%}
<div class="container mt-3">
    <form action="{% url 'app_photo:edit_image' data.id %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <img src="{{ data.image.url }}" width="360" alt="" style="">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Description</label>
            <input type="text" value="{{data.description}}" name="description">
            <span>{{form.errors.description}}</span>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
         <button type="submit" class="btn btn-primary">Reset</button>
    </form>
</div>
{%endblock%}

app_photo/templates/app_photo/image_gallery.html
{% extends "users/base_form.html" %}
{% block content %}
<style>
    .card {
        height: 100%;
        display: flex;
        flex-direction: column;
        margin-bottom: 20px; /* Добавим отступ между карточками */
    }

    .card-img-top {
        flex: 1;
        object-fit: cover;
    }

    .card-body {
        flex-grow: 0;
    }

    .card-text {
        margin-bottom: 0;
    }

    /* Стили для кнопок внутри карточки */
    .card-buttons {
        display: flex;
        justify-content: space-between; /* Равномерно распределяем кнопки по ширине */
    }
    .custom-btn {
        display: inline-block;
        padding: 8px 16px; /* увеличим отступы для кнопок */
        margin-bottom: 0;
        font-size: 16px; /* увеличим размер шрифта */
        font-weight: 400;
        line-height: 1.5;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        cursor: pointer;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        color: #fff;
        background-color: #007bff; /* изменяем фон кнопки на синий цвет */
        border-color: #007bff;
        min-width: 120px; /* установим минимальную ширину для кнопок */
    }

    .custom-btn:not(:last-child) {
        margin-right: 8px; /* уменьшим расстояние между кнопками */
    }
</style>
<div class="container mt-3">
        <h1 class="mb-4">Галерея медіафайлів</h1>
            <div class="row">
        {% for data in image_data %}
        <div class="col-md-6 mb-4">
            <div class="card">
                {% if data.file_type == 'image' %}
                <img src="{{ data.url }}" class="card-img-top" alt="{{ data.description }}">
                {% elif data.file_type == 'text' %}
                <div class="card-body text-center">
                    <span style="font-size: 5rem;">📄</span>
                </div>
                {% elif data.file_type == 'video' %}
                <div class="card-body">
                    <video controls class="card-img-top" style="max-width: 100%;">
                        <source src="{{ data.url }}" type="video/mp4">
                        Ваш браузер не підтримує відео.
                    </video>
                </div>
                {% endif %}
                <div class="card-body">
                    <p class="card-text">{{ data.description }}</p>
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'app_photo:edit_image' data.id %}" class="custom-btn">Edit</a>
                        <a href="{% url 'app_photo:remove_image' data.id %}" class="custom-btn">Delete</a>
                        <a href="{% url 'app_photo:download_image' data.id %}" class="custom-btn">Upload</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
        <nav class="pagination-nav ">
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not image_data.has_previous %} disabled {% endif %}"
                       href="{% if image_data.has_previous %} {% url 'app_photo:paginator_gallery' image_data.previous_page_number %} {% else %} # {% endif %}">Previous<span aria-hidden="true">→</span></a>
                </li>
                <li class="next">
                    <a class="{% if not image_data.has_next %} disabled {% endif %}"
                       href="{% if image_data.has_next %} {% url 'app_photo:paginator_gallery' image_data.next_page_number %} {% else %} # {% endif %}">Next
                        <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
</div>
{% endblock %}

app_photo/templates/app_photo/photos.html
{% extends "users/base_form.html" %}
{% block content %}
<style>
    .card {
        height: 100%;
        display: flex;
        flex-direction: column;
        margin-bottom: 20px; /* Добавим отступ между карточками */
    }

    .card-img-top {
        flex: 1;
        object-fit: cover;
    }

    .card-body {
        flex-grow: 0;
    }

    .card-text {
        margin-bottom: 0;
    }

    /* Стили для кнопок внутри карточки */
    .card-buttons {
        display: flex;
        justify-content: space-between; /* Равномерно распределяем кнопки по ширине */
    }
    .custom-btn {
        display: inline-block;
        padding: 8px 16px; /* увеличим отступы для кнопок */
        margin-bottom: 0;
        font-size: 16px; /* увеличим размер шрифта */
        font-weight: 400;
        line-height: 1.5;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        cursor: pointer;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
        min-width: 120px; /* установим минимальную ширину для кнопок */
    }

    .custom-btn:not(:last-child) {
        margin-right: 8px; /* уменьшим расстояние между кнопками */
    }


</style>
<div class="container">
    <h1>Фото галерея:</h1>

    <div class="row">
        {% for data in image_data %}
        <div class="col-md-6">
            <div class="card">
                {% if data.file_type == 'image' %}
                <img src="{{ data.url }}" class="card-img-top" alt="{{ data.description }}">
                <div class="card-body">
                    <p class="card-text">{{ data.description }}</p>
                    <div class="card-buttons">
                        <a href="{% url 'app_photo:edit_image' data.id %}" class="custom-btn">Edit</a>
                        <a href="{% url 'app_photo:remove_image' data.id %}" class="custom-btn">Delete</a>
                        <a href="{% url 'app_photo:download_image' data.id %}" class="custom-btn">Download</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<nav class="pagination-nav">
    <ul class="pager">
        <li class="previous">
            <a class="{% if not image_data.has_previous %} disabled {% endif %}"
               href="{% if image_data.has_previous %} {% url 'app_photo:paginator_show_photo' image_data.previous_page_number %} {% else %} # {% endif %}">Previous<span
                    aria-hidden="true">→</span></a>
        </li>
        <li class="next">
            <a class="{% if not image_data.has_next %} disabled {% endif %}"
               href="{% if image_data.has_next %} {% url 'app_photo:paginator_show_photo' image_data.next_page_number %} {% else %} # {% endif %}">Next
                <span aria-hidden="true">→</span></a>
        </li>
    </ul>
</nav>
{% endblock %}

app_photo/templates/app_photo/upload.html
{% extends "users/base_form.html" %}
{% block content %}
<div class="container form-control">
    <h2 style="margin-bottom: 20px;">File uploader:</h2>
    <form action="{% url 'app_photo:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Description</label>
            {{ form.description }}
            <div id="emailHelp" class="form-text">Description for picture</div>
            <span>{{ form.errors.description }}</span>
        </div>
        <div class="mb-3">
            <label for="formFile" class="form-label">Default file input example</label>
            {{ form.image }}
            <span>{{ form.errors.image }}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

app_photo/templates/app_photo/videos.html
{% extends "users/base_form.html" %}
{% block content %}
<style>
    .card {
        height: 100%;
        display: flex;
        flex-direction: column;
        margin-bottom: 20px; /* Добавим отступ между карточками */
    }

    .card-img-top {
        flex: 1;
        object-fit: cover;
    }

    .card-body {
        flex-grow: 0;
    }

    .card-text {
        margin-bottom: 0;
    }

    /* Стили для кнопок внутри карточки */
    .card-buttons {
        display: flex;
        justify-content: space-between; /* Равномерно распределяем кнопки по ширине */
    }

    /* Стили для пагинации */
    .pagination-nav {
        margin-top: 20px; /* Отступ сверху */
    }

    .pager {
        display: flex;
        justify-content: space-between; /* Равномерно распределяем кнопки по ширине */
    }
    .pagination-nav .pager {
        display: flex;
        justify-content: space-between; /* Распределение кнопок по краям */
        list-style: none; /* Убираем маркеры у списка */
        padding-left: 0; /* Убираем внутренний отступ слева */
    }

    .pagination-nav .pager li {
        flex: 1; /* Равномерное распределение ширины кнопок */
        text-align: center; /* Выравнивание текста по центру */
    }

    .pagination-nav .pager li a {
        display: block;
        width: 100%; /* Кнопки на всю доступную ширину */
    }
    .custom-btn {
        display: inline-block;
        padding: 8px 16px; /* увеличим отступы для кнопок */
        margin-bottom: 0;
        font-size: 16px; /* увеличим размер шрифта */
        font-weight: 400;
        line-height: 1.5;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        cursor: pointer;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
        min-width: 120px; /* установим минимальную ширину для кнопок */
    }

    .custom-btn:not(:last-child) {
        margin-right: 8px; /* уменьшим расстояние между кнопками */
    }
</style>
<div class="container">
    <h1>Відео галерея:</h1>

    <div class="row">
        {% for data in image_data %}
        <div class="col-md-6">
            <div class="card">
                {% if data.file_type == 'video' %}
                <video controls class="card-img-top" style="max-width: 100%;">
                    <source src="{{ data.url }}" type="video/mp4">
                    Ваш браузер не підтримує відео.
                </video>
                <div class="card-body">
                    <p class="card-text">{{ data.description }}</p>
                    <div class="card-buttons">
                        <a href="{% url 'app_photo:edit_image' data.id %}" class="custom-btn">Edit</a>
                        <a href="{% url 'app_photo:remove_image' data.id %}" class="custom-btn">Delete</a>
                        <a href="{% url 'app_photo:download_image' data.id %}" class="custom-btn">Download</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <nav class="pagination-nav">
        <ul class="pager">
            <li class="previous">
                <a class="{% if not image_data.has_previous %} disabled {% endif %}"
                   href="{% if image_data.has_previous %} {% url 'app_photo:paginator_show_video' image_data.previous_page_number %} {% else %} # {% endif %}">Previous<span aria-hidden="true"></span></a>
            </li>
            <li class="next">
                <a class="{% if not image_data.has_next %} disabled {% endif %}"
                   href="{% if image_data.has_next %} {% url 'app_photo:paginator_show_video' image_data.next_page_number %} {% else %} # {% endif %}">Next
                    <span aria-hidden="true"></span></a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}