app_jull/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls")),
    path("", include("app_photo.urls")),
    path("", include("notes.urls")),
    path("users/", include("users.urls")),
]

news/urls.py
from django.urls import path

from . import views
from users import views as users_views

app_name = "news"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", users_views.loginuser, name="login"),
    path("articles/", views.all_articles, name="all_articles"),
    path("article/<str:title>", views.one_article, name="one_article"),
    path("siences/", views.all_siences, name="all_siences"),
    path("sience/<str:title>", views.one_sience, name="one_sience"),
    path("technos/", views.all_technos, name="all_technos"),
    path("techno/<str:title>", views.one_techno, name="one_techno"),
    path("sports/", views.all_sports, name="all_sports"),
    path("sport/<str:title>", views.one_sport, name="one_sport"),
    path("usds/", views.all_banks_usd, name="all_banks_usd"),
    path("eurs/", views.all_banks_eur, name="all_banks_eur"),
    path("weather/", views.all_weather_cities, name="all_weather_cities"),
    path("weather/details", views.all_weather_details, name="all_weather_details"),
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'notes'

urlpatterns = [
    path("users/profile/my_notes/", views.show_notes, name="notes_list"),
    path("users/profile/my_notes/add_notes", views.add_notes, name="add_notes"),
    path("users/profile/my_notes/delete_notes/<int:notes_id>/", views.delete_note, name="delete_notes"),
    path("users/profile/my_notes/edit_notes/<int:notes_id>/", views.edit_note, name="edit_notes"),
    path("users/profile/my_notes/search_note/", views.search_notes, name="search_notes"),
    path('users/profile/notes_by_tag/<str:tag>/', views.notes_by_tag, name='notes_by_tag'),
    path("users/profile/my_notes/<int:page>", views.show_notes, name="paginator_notes_list"),

]

notes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from django.contrib.auth import get_user_model


# Create your models here.




# class Note(models.Model):
#     content = models.TextField()
#     tags = models.CharField(max_length=100, blank=True)


class Tag(models.Model):
    tag = models.CharField(max_length=200)

class Note(models.Model):
    content = models.TextField()
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,null=True)

notes/forms.py
from django.forms import ModelForm, CharField, ImageField, TextInput, FileInput, FileField

from .models import Note


class NoteForm(ModelForm):
    content = CharField(max_length=1000,widget=TextInput(attrs={'class':'form-control', 'id':'exampleInputEmail1'}))
    tags = CharField(max_length=1000,widget=TextInput(attrs={'class':'form-control', 'id':'exampleInputEmail1'}))

    class Meta:
        model = Note
        fields = ['content', 'tags']


class SearchNoteForm(ModelForm):
    tags = CharField(max_length=1000, widget=TextInput(attrs={'class': 'form-control', 'id': 'exampleInputEmail1'}))

    class Meta:
        model = Note
        fields = ['tags']

notes/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect

from .forms import NoteForm,SearchNoteForm
from .models import Note, Tag
from django.contrib import messages

# Create your views here.


def show_notes(request,page=1):
    user=request.user
    notes = Note.objects.filter(user=user)
    paginator = Paginator(notes, 5)
    try:
        notes = paginator.page(page)
    except PageNotAnInteger:
        notes = paginator.page(1)
    except EmptyPage:
        notes = paginator.page(paginator.num_pages)
    return render(request, "notes/mynotes.html", context={"notes": notes})


def delete_note(request, notes_id):
    try:
        note = Note.objects.get(id=notes_id)
        note.delete()
        return redirect(to='notes:notes_list')
    except Note.DoesNotExist:
        return redirect(to='notes:notes_list')


def edit_note(request, notes_id):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            tags_input = form.cleaned_data['tags']
            # Розділіть введені теги на окремі теги
            tags_list = [tag.strip() for tag in tags_input.split()]
            # Отримайте запис для редагування
            note = Note.objects.get(id=notes_id)
            note.content = content
            note.save()  # Зберегти зміни у записі
            # Очистити старі теги
            note.tags.clear()
            # Додати нові теги
            for tag_name in tags_list:
                tag, created = Tag.objects.get_or_create(tag=tag_name)
                note.tags.add(tag)
            return redirect('notes:notes_list')
    else:
        note = Note.objects.get(id=notes_id)
        # Створити форму з даними про запис
        form = NoteForm(initial={'content': note.content, 'tags': ' '.join(note.tags.values_list('tag', flat=True))})
    return render(request, 'notes/edit_note.html', {'form': form})


def add_notes(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.save()
            tag_data = form.cleaned_data['tags']
            tag_names = tag_data.split()  # Перетворити рядок тегів на список
            for tag_name in tag_names:
                tag, created = Tag.objects.get_or_create(tag=tag_name.strip())
                note.tags.add(tag)  # Додати тег до запису
            messages.success(request, 'Заметка успешно создана.')
            return redirect('notes:notes_list')
        else:
            # Если форма не прошла валидацию, добавляем сообщение об ошибке
            messages.error(request, 'Заметка не создана. Пожалуйста, заполните все поля формы.')
    else:
        form = NoteForm()
    return render(request, 'notes/add_notes.html', {'form': form})


def search_notes(request):
    if request.method == 'POST':
        form = SearchNoteForm(request.POST)
        if form.is_valid():
            tags = form.cleaned_data['tags']
            # Виконати логіку пошуку за тегами та отримати результати
            notes = Note.objects.filter(tags__tag__icontains=tags)
            return render(request, 'notes/search_results.html', {'notes': notes, 'form': form})
    else:
        form = SearchNoteForm()
    return render(request, 'notes/search_notes.html', {'form': form})


def notes_by_tag(request, tag):
    user = request.user
    notes = Note.objects.filter(tags__tag__iexact=tag, user=user)
    if not notes.exists():
        messages.info(request, f'Заметок с тегом "{tag}" не найдено.')
    return render(request, 'notes/notes_by_tag.html', {'notes': notes, 'tag': tag})

notes/templates/notes/add_notes.html
{% extends "users/base_form.html" %}
{% block content %}

<div class="container form-control">
    <h1>Add New Note</h1>
    <form action="{% url 'notes:add_notes' %}" method="post">
        {% csrf_token %}

        <!-- Вывод сообщений об успехе и ошибках -->
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="form-group">
            <label for="content">Content:</label>
            <textarea id="content" name="content" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label for="tags">Tags:</label>
            <input type="text" id="tags" name="tags" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

{% endblock %}

notes/templates/notes/edit_note.html
{% extends "users/base_form.html" %}
{% block content %}
<div class="container form-control">
    <h1>Edit Note</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="content">Content:</label>
            <textarea id="content" name="content" class="form-control">{{ form.initial.content }}</textarea>
        </div>
        <div class="form-group">
            <label for="tags">Tags:</label>
            <input type="text" id="tags" name="tags" class="form-control" value="{{ form.initial.tags }}">
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock %}

notes/templates/notes/mynotes.html
{% extends "users/base_form.html" %}
{% block content %}

<div class="container form-control">
    <h1>Note List</h1>
    {% if notes %}
    <ul class="list-group">
        {% for note in notes %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-10">
                    <h4>{{ note.content }}</h4>
                    <div class="tags">
                        <p>Tags: {% for tag in note.tags.all %}<a class="all_tags" href="{% url 'notes:notes_by_tag' tag.tag %}">{{ tag.tag }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="" role="group" aria-label="Note Actions">
                        <a href="{% url 'notes:edit_notes' note.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'notes:delete_notes' note.id %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </li>
        {% endfor %}
        {% else %}
        <p>No notes</p>
        {% endif %}
    </ul>
</div>
 <nav class="pagination-nav">
            <ul class="pager" >

                <li class="previous">
                    <a class="{% if not notes.has_previous %} disabled {% endif %}"
                       href="{% if notes.has_previous %} {% url 'notes:paginator_notes_list' notes.previous_page_number %} {% else %} # {% endif %}">Previous<span aria-hidden="true">→</span></a>
                </li>
                <li class="next">
                    <a class="{% if not notes.has_next %} disabled {% endif %}"
                       href="{% if notes.has_next %} {% url 'notes:paginator_notes_list' notes.next_page_number %} {% else %} # {% endif %}">Next
                        <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
{% endblock %}

notes/templates/notes/notes_by_tag.html
{% extends "users/base_form.html" %}
{% block content %}
<div class="container form-control">
    <h1>Notes with Tag: {{ tag }}</h1>
    <ul class="list-group">
        {% for note in notes %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-10">
                    <h4>{{ note.content }}</h4>
                </div>
                <div class="col-md-2">
                    <div class="" role="group" aria-label="Note Actions">
                        <a href="{% url 'notes:edit_notes' note.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'notes:delete_notes' note.id %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>

</div>
{% endblock %}

notes/templates/notes/search_notes.html
{% extends "users/base_form.html" %}
{% block content %}
<div class="container form-control">
    <h1>Search Notes</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="tags">Tags:</label>
            <input type="text" id="tags" name="tags" class="form-control" placeholder="Enter tags">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</div>
{% endblock %}

notes/templates/notes/search_results.html
{% extends "users/base_form.html" %}
{% block content %}

<div class="container form-control">
    <h1>Search Results</h1>
    {% if notes %}
    <ul class="list-group">
        {% for note in notes %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-10">
                    <h4>{{ note.content }}</h4>
                </div>
                <div class="col-md-2">
                    <div class="" role="group" aria-label="Note Actions">
                        <a href="{% url 'notes:edit_notes' note.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'notes:delete_notes' note.id %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </li>
        {% endfor %}
        {% else %}
        <p>No notes found.</p>
        {% endif %}
    </ul>
    <a href="{% url 'notes:search_notes' %}" class="btn btn-primary mt-3">New Search</a>
</div>

{% endblock %}