app_jull/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls")),
    path("", include("app_photo.urls")),
    path("", include("notes.urls")),
    path("users/", include("users.urls")),
]

app_photo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'app_photo'

urlpatterns = [
    path('users/profile/gallery/upload/', views.upload, name='upload'),
    path('users/profile/gallery/', views.show_images, name='gallery'),
    path('users/profile/gallery/delete/<int:image_id>/', views.delete_image, name='remove_image'),
    path('users/profile/gallery/edit/<int:image_id>/', views.edit_image, name='edit_image'),
    path('users/profile/gallery/download/<int:image_id>/', views.download_image, name='download_image'),
    path('users/profile/gallery/my_photo', views.show_all_photo, name='show_photo'),
    path('users/profile/gallery/my_video', views.show_all_video, name='show_video'),
    path('users/profile/gallery/another', views.show_all_another, name='show_another'),
    path('users/profile/gallery/<int:page>', views.show_images, name='paginator_gallery'),
    path('users/profile/gallery/my_photo/<int:page>', views.show_all_photo, name='paginator_show_photo'),
    path('users/profile/gallery/my_video/<int:page>', views.show_all_video, name='paginator_show_video'),
    path('users/profile/gallery/another/<int:page>', views.show_all_another, name='paginator_show_another')
]

news/urls.py
from django.urls import path

from . import views
from users import views as users_views

app_name = "news"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", users_views.loginuser, name="login"),
    path("articles/", views.all_articles, name="all_articles"),
    path("article/<str:title>", views.one_article, name="one_article"),
    path("siences/", views.all_siences, name="all_siences"),
    path("sience/<str:title>", views.one_sience, name="one_sience"),
    path("technos/", views.all_technos, name="all_technos"),
    path("techno/<str:title>", views.one_techno, name="one_techno"),
    path("sports/", views.all_sports, name="all_sports"),
    path("sport/<str:title>", views.one_sport, name="one_sport"),
    path("usds/", views.all_banks_usd, name="all_banks_usd"),
    path("eurs/", views.all_banks_eur, name="all_banks_eur"),
    path("weather/", views.all_weather_cities, name="all_weather_cities"),
    path("weather/details", views.all_weather_details, name="all_weather_details"),
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'notes'

urlpatterns = [
    path("users/profile/my_notes/", views.show_notes, name="notes_list"),
    path("users/profile/my_notes/add_notes", views.add_notes, name="add_notes"),
    path("users/profile/my_notes/delete_notes/<int:notes_id>/", views.delete_note, name="delete_notes"),
    path("users/profile/my_notes/edit_notes/<int:notes_id>/", views.edit_note, name="edit_notes"),
    path("users/profile/my_notes/search_note/", views.search_notes, name="search_notes"),
    path('users/profile/notes_by_tag/<str:tag>/', views.notes_by_tag, name='notes_by_tag'),
    path("users/profile/my_notes/<int:page>", views.show_notes, name="paginator_notes_list"),

]

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("contacts/", views.contact_list, name="contacts"),
    path("contact/create/", views.contact_create, name="contact_create"),
    path("contact/<int:pk>/edit/", views.contact_edit, name="contact_edit"),
    path("contact/<int:pk>/delete/", views.contact_delete, name="contact_delete"),
    path('upcoming_birthdays/', views.upcoming_birthdays, name='upcoming_birthdays'),
    path('contacts/search/', views.contact_search, name='contact_search'),
    path('contacts/<int:pk>/delete/confirm/', views.contact_confirm_delete, name='contact_confirm_delete'),
    path('users/profile/add_avatar/', views.add_avatar, name='add_avatar_url'),
    path('users/profile/change-avatar/', views.choose_new_avatar, name='change_avatar_profile'),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path("reset-password/done/", PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name="password_reset_done"),
    path("reset-password/confirm/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url="/users/reset-password/complete/"),
         name="password_reset_confirm"),
    path("reset-password/complete/",
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

    path('users/profile/add_avatar/', views.add_avatar, name='add_avatar_url'),
    path("contacts/<int:page>", views.contact_list, name="paginator_contacts"),


]

users/models.py
from django.core.validators import RegexValidator, EmailValidator
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    date_of_birth = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True)
    is_verified = models.BooleanField(default=False)
    groups = models.ManyToManyField("auth.Group", related_name="custom_user_groups", blank=True)
    user_permissions = models.ManyToManyField("auth.Permission", related_name="custom_user_permissions", blank=True)

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

             
class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars', max_length=200,null=True, blank=True)


    def __str__(self):
        return self.user.username


class Contact(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.TextField()
    phone_number = models.CharField(max_length=20, validators=[RegexValidator(regex=r'^\+?1?\d{10,13}$', message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.")])
    email = models.EmailField(validators=[EmailValidator(message="Invalid email format")])
    birthday = models.DateField()

    def __str__(self):
        return self.name

users/forms.py
from django import forms


from .models import CustomUser, Profile, Contact


class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput, required=True)
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"required": "required"}))
    date_of_birth = forms.DateField(label='Date of Birth', widget=forms.DateInput(attrs={"required": "required", "type": "date"}))

    class Meta:
        model = CustomUser
        fields = ("username", "email", "date_of_birth")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(max_length=200,widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'address', 'phone_number', 'email', 'birthday']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

users/views.py
import cloudinary.uploader
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from datetime import datetime, timedelta


from .forms import SignUpForm, LoginForm, ProfileForm, ContactForm
from .models import Profile, Contact
from django.utils import timezone
from app_photo.models import Picture
today = timezone.now().date()
yesterday = today - timezone.timedelta(days=1)

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("news:index")
        # else:
        #     # Обработка ошибок для отдельных полей
        #     for field in form.errors:
        #         for error in form.errors[field]:
        #             messages.error(request, f"{field}: {error}")
    else:
        form = SignUpForm()
    return render(request, "users/signup.html", {"form": form})


def loginuser(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('users:profile')
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Please enter both username and password.')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to="news:index")


today = timezone.now().date()
yesterday = today - timezone.timedelta(days=1)

@login_required
def profile(request):
    user = request.user
    contacts_count = Contact.objects.filter(user=user).count()
    current_time = datetime.now()
    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=request.user)


    user.last_profile_visit = timezone.now()
    user.save()

    if request.method == "POST":
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, "Your profile has been updated successfully.")
            return redirect("users:profile")
    else:
        profile_form = ProfileForm(instance=profile)
    last_login_time = user.last_login
    context = {
        "profile": profile,
        "profile_form": profile_form,
        "contacts_count": contacts_count,
        "last_login_time": last_login_time,
        "current_time": current_time,
    }
    return render(request, "users/profile.html", context=context)


@login_required
def contact_list(request,page=1):
    user_contacts = Contact.objects.all()
    user = request.user
    user_contacts = Contact.objects.filter(user=user.id)
    paginator = Paginator(user_contacts, 5)
    try:
        user_contacts = paginator.page(page)
    except PageNotAnInteger:
        user_contacts = paginator.page(1)
    except EmptyPage:
        user_contacts = paginator.page(paginator.num_pages)
    return render(request, "users/contacts.html", {"contacts": user_contacts})


@login_required
def contact_create(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return redirect("users:contacts")
    else:
        form = ContactForm()
    return render(request, "users/contact_create.html", {"form": form})



def contact_edit(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    if request.method == "POST":
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect("users:contacts")
    else:
        form = ContactForm(instance=contact)
    return render(request, "users/contact_edit.html", {"form": form})


def contact_delete(request, pk):

    contact = get_object_or_404(Contact, pk=pk)
    
    if request.method == "POST":

        contact.delete()

        # messages.success(request, 'Contact successfully deleted.')
        
        return redirect("users:contacts")
    

    return render(request, "users/contact_confirm_delete.html", {"contact": contact})
    
def upcoming_birthdays(request):
    days = int(request.GET.get('days', 7))
    current_date = datetime.now().date()
    future_date = current_date + timedelta(days=days)
    
    upcoming_contacts = Contact.objects.filter(
        birthday__range=[current_date, future_date]
    ).order_by("birthday")
    
    return render(request, "users/upcoming_birthdays.html", {
        "upcoming_contacts": upcoming_contacts,
        "days": days
    })


def contact_search(request):
    query = request.GET.get('query')
    if query:
      
        contacts = Contact.objects.filter(
            Q(name__icontains=query) |
            Q(address__icontains=query) |
            Q(phone_number__icontains=query) |
            Q(email__icontains=query) |
            Q(birthday__icontains=query) 
        )
    else:
        contacts = Contact.objects.all()
    return render(request, 'users/contacts.html', {'contacts': contacts})
def contact_confirm_delete(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    return render(request, 'users/contact_confirm_delete.html', {'contact': contact})

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = "users/password_reset_subject.txt"



@login_required
def add_avatar(request):
    if request.method == 'POST':
        user = request.user
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            avatar_file = request.FILES.get('avatar')

            uploaded_file = cloudinary.uploader.upload(avatar_file, resource_type="image")
            profile = Profile.objects.get_or_create(user=user)[0]
            profile.avatar = uploaded_file['url']
            profile.save()
            messages.success(request, "Avatar successfully changed", extra_tags='success')
            return redirect('users:profile')
        else:
            messages.error(request, "You didn't choose the file")
    return render(request, "users/change_avatar_profile.html")


def choose_new_avatar(request):
    return render(request, "users/change_avatar_profile.html")


def some_view(request):
    request_paths = ['/users/login/', '/users/signup/']
    return render(request, 'base_form.html', {'request_paths': request_paths})

users/templates/users/base_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0,
        minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.2/zxcvbn.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="icon" href="{% static 'Icon_jull.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}">

    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'app_photo/style.css' %}"> {% endcomment %}
    <title>Jull</title>
</head>
<style>
    .main_head_title {
    font-size: 50px;
    background: linear-gradient(#801010, #0d0e0d);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    }
    .top_container {
    text-align: left;
    margin-bottom: 40px;
    padding: 10px;
    background: linear-gradient(#382288, #f3d840, #607fa3);
    }
    .footer_container {
        background: linear-gradient(#152d47, #f3d840, #382288);
    }
</style>
<body>
    <div class="top_container">
            <div class="row header-box pt-3 mb-3">
                <div class="col-md-8">
                    <h1 class="main_head_title">
                        <a href="/" style="text-decoration:none">
                            <img src="{% static 'web_world.ico' %}" alt="Web.World" >
                            Jull assistant</a>
                    </h1>
                </div>
                <div class="button_main">
                    {% if request.path == "/users/profile/" %}
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="{% url 'users:contacts' %}" class="btn btn-work">My Contacts</a>
                            <a href="{% url 'app_photo:gallery' %}" class="btn btn-work">Gallery</a>
                            <a href="{% url 'notes:notes_list' %}" class="btn btn-work">My Notes</a>
                            <a href="{% url 'users:password_reset' %}" class="btn btn-primary reset-password">Reset Password</a>
                            <a href="{% url 'users:logout' %}" class="btn btn-logout">Logout</a>
                        </div>
                    {% else %}
                            {% if request.path != '/users/login/' and request.path != '/users/signup/' %}
                                <a href="{% url 'users:profile' %}" class="btn btn-profile">My Profile</a>
                            {% endif %}
                            
                            {% if request.path == "/users/profile/my_notes/" %}
                                <a href="{% url 'notes:add_notes' %}" class="btn btn-primary btn-addnote">Add New Note</a>
                                <a href="{% url 'notes:search_notes' %}" class="btn btn-primary btn-searchnote">Search Notes</a>
                            {% endif %}

                            {% if request.path == "/users/profile/my_notes/search_note/" or "/users/profile/my_notes/edit_notes/" in request.path or "/users/profile/notes_by_tag/" in request.path or request.path == "/users/profile/my_notes/add_notes" %}
                                <a href="{% url 'notes:notes_list' %}" class="btn btn-primary btn-mynotes">My Notes</a>
                            {% endif %}

                            {% if request.path == "/users/profile/gallery/" %}
                                <a href="{% url 'app_photo:show_photo' %}" class="btn btn-primary btn-myphoto">My photos</a>
                                <a href="{% url 'app_photo:show_video' %}" class="btn btn-primary btn-myvideo">My video</a>
                                <a href="{% url 'app_photo:show_another' %}" class="btn btn-primary btn-anotherfiles">Another files</a>
                                <a href="{% url 'app_photo:upload' %}" class="btn btn-primary btn-upload">Upload</a>
                            {% endif %}

                            {% if request.path == "/users/profile/gallery/my_photo" or request.path == "/users/profile/gallery/my_video" or request.path == "/users/profile/gallery/upload/" or request.path == "/users/profile/gallery/another" %}
                                <a href="{% url 'app_photo:gallery' %}" class="btn btn-primary btn-myphotogalery">Gallery</a>
                            {% endif %}
                    {% endif %}
                </div>
                {% if request.path not in request_paths %}
                {% endif %}
                {% if request.path == "/users/profile/my_notes/" %}
                    <a href="{% url 'notes:add_notes' %}" class="btn btn-primary btn-addnote">Add New Note</a>
                    <a href="{% url 'notes:search_notes' %}" class="btn btn-primary btn-searchnote">Search Notes</a>
                {% endif %}
        
            {% if request.path == "/users/profile/my_notes/search_note/" %}
                <a href="{% url 'notes:notes_list' %}" class="btn btn-primary btn-mynotes">My Notes</a>
            {% endif %}
        
            {% if "/users/profile/my_notes/edit_notes/" in request.path %}
                <a href="{% url 'notes:notes_list' %}" class="btn btn-primary btn-mynotes">My Notes</a>
            {% endif %}
        
            {% if "/users/profile/notes_by_tag/" in request.path %}
                <a href="{% url 'notes:notes_list' %}" class="btn btn-primary btn-mynotes">My Notes</a>
            {% endif %}
        
            {% if request.path == "/users/profile/my_notes/add_notes" %}
                <a href="{% url 'notes:notes_list' %}" class="btn btn-primary btn-mynotes">My Notes</a>
            {% endif %}
        
            {% if request.path == "/users/profile/gallery/" %}
                <a href="{% url 'app_photo:show_photo' %}" class="btn btn-primary btn-myphoto">My photos</a>
                <a href="{% url 'app_photo:show_video' %}" class="btn btn-primary btn-myvideo">My video</a>
                <a href="{% url 'app_photo:show_another' %}" class="btn btn-primary btn-anotherfiles">Another files</a>
                <a href="{% url 'app_photo:upload' %}" class="btn btn-primary btn-upload">Upload</a>
            {% endif %}
        </div>        
    </div>
    </div>
        {% comment %} <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <p>by WebWorld Corporation</p>
                        <img src="{% static 'Umbrella_logo.ico' %}" alt="Umbrella Corporation Logo" >
                    </div>
                </div>
            </div>
        </footer> {% endcomment %} 
        {% block content %} {% endblock %}
        <div style="padding: 150px;">
        <div class="footer_container bg-primary footer_text mt-5 px-sm-3 px-md-5 fixed-bottom">
            <div class="container text-center py-5">
                <p class="m-0">
                    <a href="/"><img src="{% static 'web_world.ico' %}" alt="Web.World"></a>
                    <a class="footer_text font-weight-bold">Web.World</a> - Corporation</p>
            </div>
        </div>
        </div>
</body>
</html>

users/templates/users/change_avatar_profile.html
{% extends "users/base_form.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">Change Avatar</h2>
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.tags == 'success' %}
                                <div class="alert alert-success">{{ message }}</div>
                            {% else %}
                                <div class="alert alert-danger">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <button type="button" class="close" aria-label="Close" onclick="redirectToHome()">
                        <span aria-hidden="true" style="font-weight: bold;">&times;</span>
                    </button>         
                </div>               
                <div class="card-body">
                    <form id="avatar-form" action="{% url 'users:add_avatar_url' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="file" id="id_avatar" name="avatar" class="form-control-file" onchange="previewImage(event)">
                            <span class="text-danger">{{ profile_form.avatar.errors }}</span>
                        </div>
                        <div class="form-group" id="avatar-preview-container" style="display: none;">
                            <img id="avatar-preview" src="#" alt="Preview"  class="avatar-img img-fluid rounded-circle" style="width: 150px; height: 150px;">
                        </div>
                        <button type="submit" class="btn btn-success">Save Changes</button>
                        <button type="button" class="btn btn-danger ml-2" onclick="resetForm()">Reset</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
function redirectToHome() {
    window.location.href = "{% url 'users:profile' %}";
}
</script>
<script>
function previewImage(event) {
    var reader = new FileReader();
    reader.onload = function(){
        var output = document.getElementById('avatar-preview');
        output.src = reader.result;
        document.getElementById('avatar-preview-container').style.display = 'block';
    }
    reader.readAsDataURL(event.target.files[0]);
}

function resetForm() {
    document.getElementById('avatar-form').reset();
    document.getElementById('avatar-preview-container').style.display = 'none';
}

function validateForm() {
    var fileInput = document.getElementById('id_avatar');
    if (fileInput.files.length === 0) {
        alert('Выберите файл, пожалуйста.');
        return false; // Отменить отправку формы
    }
    return true; // Продолжить отправку формы
}
</script>
{% endblock %}

users/templates/users/contacts.html
{% extends "users/base_form.html" %}
{% block content %}
<div class="container contact-list-container">
    <h2 class="contact-list-header text-center mb-4">Contact List</h2>
    <form method="GET" class="search-form mb-4" action="{% url 'users:contact_search' %}">
        <div class="input-group">
            <input type="text" name="query" class="form-control" placeholder="Search by name, address, phone, email, or birthday">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
            </div>
        </div>
    </form>
    <div class="row mb-3">
        <div class="col text-center">
            <a href="{% url 'users:contact_create' %}" class="btn btn-primary mr-2">Add Contact</a>
            <a href="{% url 'users:upcoming_birthdays' %}" class="btn btn-info mr-2">Upcoming Birthdays</a>
            <a href="{% url 'users:profile' %}" class="btn btn-primary">Back to Profile</a>
        </div>
    </div>
    {% if contacts %}
    <div class="row">
        <div class="col">
            <ul class="list-group">
                {% for contact in contacts %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div class="contact-info">
                        <strong>Name:</strong> {{ contact.name }}<br>
                        <strong>Address:</strong> {{ contact.address }}<br>
                        <strong>Phone Number:</strong> {{ contact.phone_number }}<br>
                        <strong>Email:</strong> {{ contact.email }}<br>
                        <strong>Birthday:</strong> {{ contact.birthday }}<br>
                    </div>
                    <div class="contact-actions">
                        <a href="{% url 'users:contact_edit' contact.pk %}" class="btn btn-sm btn-info mr-2">Edit</a>
                        <a href="{% url 'users:contact_confirm_delete' contact.pk %}" class="btn btn-sm btn-danger">Delete</a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <nav aria-label="Contacts navigation" class="mt-4">
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not contacts.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if contacts.has_previous %}{% url 'users:paginator_contacts' contacts.previous_page_number %}{% else %}#{% endif %}">Previous</a>
            </li>
            <li class="page-item {% if not contacts.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if contacts.has_next %}{% url 'users:paginator_contacts' contacts.next_page_number %}{% else %}#{% endif %}">Next</a>
            </li>
        </ul>
    </nav>
    {% else %}
    <p class="no-contacts text-center">You have no contacts yet.</p>
    {% endif %}
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "users/base_form.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center" style="height: 100vh;">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-body p-5">
                    <h2 class="card-title text-center mb-4">Password reset complete!</h2>
                    <p class="card-text text-center">Your password has been successfully reset.</p>
                    <div class="text-center mt-4">
                        {% if user.is_authenticated %}
                            <a href="{% url 'users:profile' %}" class="btn btn-profile-pass-comp">My Profile</a>
                        {% else %}
                            <a href="{% url 'users:login' %}" class="btn btn-work">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}